### ISSUE TITLE
Dose not seam to work with $ref in schema

### ISSUE THREAD

**Issue by nbaillie** [entrepreneur-interet-general/open_api_schemas_to_markdown#4]
Dose not seam to work with $ref in schema, added a print to the statement and seeing the bellow:

`
OrderedDict([('type', 'string')])
OrderedDict([('type', 'int')])
OrderedDict([('type', 'integer'), ('format', 'int')])
OrderedDict([('type', 'string')])
OrderedDict([('type', 'string')])
OrderedDict([('type', 'integer'), ('format', 'int')])
OrderedDict([('type', 'string')])
OrderedDict([('type', 'string')])
OrderedDict([('type', 'boolean')])
OrderedDict([('$ref', '#/components/schemas/Organisation')])
Traceback (most recent call last):
  File "/Users/neil.baillie/.pyenv/versions/3.7.5rc1/bin/oa-to-md", line 27, in <module>
    converter.convert()
  File "/Users/neil.baillie/.pyenv/versions/3.7.5rc1/lib/python3.7/site-packages/open_api_schemas_to_markdown/converter.py", line 29, in convert
    ObjectFormatter(object_name, values, self.locale).format()
  File "/Users/neil.baillie/.pyenv/versions/3.7.5rc1/lib/python3.7/site-packages/open_api_schemas_to_markdown/converter.py", line 56, in format
    type=self.type(values),
  File "/Users/neil.baillie/.pyenv/versions/3.7.5rc1/lib/python3.7/site-packages/open_api_schemas_to_markdown/converter.py", line 98, in type
    return values['type']
KeyError: 'type`

**Comment by AntoineAugusti** [comment]
Hello,

I can confirm that I did not try to implement this feature.

**Comment by nbaillie** [comment]
Thanks for the quick response. Appreciated.
