### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by suyashcjoshi** [entrepreneur-interet-general/open_api_schemas_to_markdown#5]
Getting this error :

```
Traceback (most recent call last):
  File "/usr/local/bin/oa-to-md", line 27, in <module>
    converter.convert()
  File "/usr/local/lib/python3.9/site-packages/open_api_schemas_to_markdown/converter.py", line 29, in convert
    ObjectFormatter(object_name, values, self.locale).format()
  File "/usr/local/lib/python3.9/site-packages/open_api_schemas_to_markdown/converter.py", line 56, in format
    type=self.type(values),
  File "/usr/local/lib/python3.9/site-packages/open_api_schemas_to_markdown/converter.py", line 97, in type
    return values['type']
KeyError: 'type'
```

**Comment by ahaha-vip** [comment]
same error
